In [ ]:
'''DIFFERENT WAYS OF CREATING DATAFRAME'''
 1.Using CSV
 2.Using Excel
 3.From python dictionary
 4.From list of tuplies
 5.From list of dictionaries

In [4]:
import pandas as pd
df = pd.read_csv(r'C:\Users\BHAVANIPRASADKARRI\OneDrive\Desktop\jupyter notebook\weather_data.csv')
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [14]:
import pandas as pd 
df = pd.read_csv("weather_data.csv.csv")
df

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow

In [37]:
df = pd.read_excel(r'C:\Users\BHAVANIPRASADKARRI\OneDrive\Desktop\jupyter notebook\weather_data.xlsx')
 df

IndentationError: unexpected indent (724800635.py, line 2)